vars:
  pip_install_packages:
    - name: docker
  datadog_api_key: "{{DATADOG_API_KEY}}"
  datadog_site: "datadoghq.eu"
  datadog_checks:
    http_check:
      init_config:
      instances:
        - name: website
          url: "{{WEBSITE_URL}}"
        - name: droplet
          url: "{{DROPLET_URL}}"
